#!/bin/bash

sed -i '73a System.out.println("[msx] before_class");' hadoop-hdfs/src/test/java/org/apache/hadoop/security/TestPermissionSymlinks.java
sed -i '81a System.out.println("[msx] before_class");' hadoop-hdfs/src/test/java/org/apache/hadoop/metrics2/sink/TestRollingFileSystemSinkWithSecureHdfs.java
sed -i '55a System.out.println("[msx] before_class");' hadoop-hdfs/src/test/java/org/apache/hadoop/TestGenericRefresh.java
sed -i '65a System.out.println("[msx] before_class");' hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/client/impl/TestBlockReaderLocal.java
sed -i '59a System.out.println("[msx] before_class");' hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/client/impl/TestBlockReaderLocalLegacy.java
sed -i '48a System.out.println("[msx] before_class");' hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/client/impl/TestClientBlockVerification.java
sed -i '36a System.out.println("[msx] before_class");' hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/TestParallelShortCircuitRead.java
sed -i '78a System.out.println("[msx] before_class");' hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/TestHDFSPolicyProvider.java
sed -i '86a System.out.println("[msx] before_class");' hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/TestDFSOutputStream.java
sed -i '99a System.out.println("[msx] before_class");' hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/security/TestDelegationTokenForProxyUser.java
sed -i '51a System.out.println("[msx] before_class");' hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/TestDatanodeConfig.java
sed -i '69a System.out.println("[msx] before_class");' hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/TestHDFSTrash.java
sed -i '26a System.out.println("[msx] before_class");' hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/TestParallelRead.java
sed -i '62a System.out.println("[msx] before_class");' hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/TestFetchImage.java
sed -i '28a System.out.println("[msx] before_class");' hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/TestParallelShortCircuitLegacyRead.java
sed -i '93a System.out.println("[msx] before_class");' hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/TestAclsEndToEnd.java
sed -i '66a System.out.println("[msx] before_class");' hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/TestListFilesInFileContext.java
sed -i '94a System.out.println("[msx] before_class");' hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/TestQuota.java
sed -i '82a System.out.println("[msx] before_class");' hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/shortcircuit/TestShortCircuitLocalRead.java
sed -i '136a System.out.println("[msx] before_class");' hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/TestSecureEncryptionZoneWithKMS.java
sed -i '75a System.out.println("[msx] before_class");' hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/TestFileAppend3.java
sed -i '62a System.out.println("[msx] before_class");' hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/FileAppendTest4.java
sed -i '87a System.out.println("[msx] before_class");' hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/net/TestDFSNetworkTopologyPerformance.java
sed -i '46a System.out.println("[msx] before_class");' hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/TestSnapshotCommands.java
sed -i '51a System.out.println("[msx] before_class");' hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/TestReadStripedFileWithDecodingCorruptData.java
sed -i '81a System.out.println("[msx] before_class");' hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/TestAppendSnapshotTruncate.java
sed -i '47a System.out.println("[msx] before_class");' hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/crypto/TestHdfsCryptoStreams.java
sed -i '47a System.out.println("[msx] before_class");' hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/TestErasureCodeBenchmarkThroughput.java
sed -i '36a System.out.println("[msx] before_class");' hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/TestParallelShortCircuitReadNoChecksum.java
sed -i '40a System.out.println("[msx] before_class");' hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/TestParallelShortCircuitReadUnCached.java
sed -i '67a System.out.println("[msx] before_class");' hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/TestFileStatus.java
sed -i '48a System.out.println("[msx] before_class");' hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/TestAppendDifferentChecksum.java
sed -i '63a System.out.println("[msx] before_class");' hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/TestIsMethodSupported.java
sed -i '70a System.out.println("[msx] before_class");' hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/web/TestWebHdfsTokens.java
sed -i '59a System.out.println("[msx] before_class");' hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/web/TestWebHdfsWithMultipleNameNodes.java
sed -i '72a System.out.println("[msx] before_class");' hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/web/TestFSMainOperationsWebHdfs.java
sed -i '53a System.out.println("[msx] before_class");' hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/web/TestHttpsFileSystem.java
sed -i '32a System.out.println("[msx] before_class");' hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/web/TestWebHDFSAcl.java
sed -i '73a System.out.println("[msx] before_class");' hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/web/TestWebHdfsWithAuthenticationFilter.java
sed -i '52a System.out.println("[msx] before_class");' hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/TestReadStripedFileWithDecodingDeletedData.java
sed -i '79a System.out.println("[msx] before_class");' hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/protocol/datatransfer/sasl/SaslDataTransferTestCase.java
sed -i '59a System.out.println("[msx] before_class");' hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/server/common/TestJspHelper.java
sed -i '58a System.out.println("[msx] before_class");' hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/server/blockmanagement/TestAvailableSpaceBlockPlacementPolicy.java
sed -i '67a System.out.println("[msx] before_class");' hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/server/blockmanagement/TestSortLocatedStripedBlock.java
sed -i '98a System.out.println("[msx] before_class");' hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/server/blockmanagement/TestReconstructStripedBlocksWithRackAwareness.java
sed -i '61a System.out.println("[msx] before_class");' hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/server/blockmanagement/TestBlockReportRateLimiting.java
sed -i '63a System.out.println("[msx] before_class");' hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/server/datanode/TestDataNodeTcpNoDelay.java
sed -i '60a System.out.println("[msx] before_class");' hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/server/datanode/TestCachingStrategy.java
sed -i '63a System.out.println("[msx] before_class");' hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/server/datanode/TestLargeBlockReport.java
sed -i '59a System.out.println("[msx] before_class");' hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/server/datanode/fsdataset/impl/TestScrLazyPersistFiles.java
sed -i '133a System.out.println("[msx] before_class");' hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/server/datanode/TestFsDatasetCache.java
sed -i '43a System.out.println("[msx] before_class");' hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/server/namenode/TestSecondaryWebUi.java
sed -i '68a System.out.println("[msx] before_class");' hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/server/namenode/TestFavoredNodesEndToEnd.java
sed -i '56a System.out.println("[msx] before_class");' hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/server/namenode/TestFSImageWithXAttr.java
sed -i '61a System.out.println("[msx] before_class");' hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/server/namenode/TestSnapshotPathINodes.java
sed -i '37a System.out.println("[msx] before_class");' hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/server/namenode/TestNNThroughputBenchmark.java
sed -i '68a System.out.println("[msx] before_class");' hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/server/namenode/TestNameNodeHttpServer.java
sed -i '30a System.out.println("[msx] before_class");' hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/server/namenode/TestNameNodeAcl.java
sed -i '49a System.out.println("[msx] before_class");' hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/server/namenode/TestEditLogFileOutputStream.java
sed -i '60a System.out.println("[msx] before_class");' hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/server/namenode/TestBlockUnderConstruction.java
sed -i '81a System.out.println("[msx] before_class");' hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/server/namenode/snapshot/TestAclWithSnapshot.java
sed -i '74a System.out.println("[msx] before_class");' hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/server/namenode/snapshot/TestXAttrWithSnapshot.java
sed -i '59a System.out.println("[msx] before_class");' hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/server/namenode/snapshot/TestDisallowModifyROSnapshot.java
sed -i '49a System.out.println("[msx] before_class");' hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/server/namenode/TestFSImageWithAcl.java
sed -i '102a System.out.println("[msx] before_class");' hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/server/namenode/FSXAttrBaseTest.java
sed -i '63a System.out.println("[msx] before_class");' hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/server/namenode/TestAllowFormat.java
sed -i '39a System.out.println("[msx] before_class");' hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/server/namenode/TestFileContextAcl.java
sed -i '72a System.out.println("[msx] before_class");' hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/server/namenode/TestDiskspaceQuotaUpdate.java
sed -i '215a System.out.println("[msx] before_class");' hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/TestDFSUpgrade.java
sed -i '39a System.out.println("[msx] before_class");' hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/TestDataStream.java
sed -i '40a System.out.println("[msx] before_class");' hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/TestListFilesInDFS.java
sed -i '109a System.out.println("[msx] before_class");' hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/TestDFSShell.java
sed -i '56a System.out.println("[msx] before_class");' hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/TestReadStripedFileWithDNFailure.java
sed -i '89a System.out.println("[msx] before_class");' hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/qjournal/TestSecureNNWithQJM.java
sed -i '36a System.out.println("[msx] before_class");' hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/TestParallelUnixDomainRead.java
sed -i '122a System.out.println("[msx] before_class");' hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/TestTrashWithSecureEncryptionZones.java
sed -i '69a System.out.println("[msx] before_class");' hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/TestExtendedAcls.java
sed -i '97a System.out.println("[msx] before_class");' hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/tools/offlineImageViewer/TestOfflineImageViewerForAcl.java
sed -i '63a System.out.println("[msx] before_class");' hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/tools/offlineImageViewer/TestOfflineImageViewerForContentSummary.java
sed -i '145a System.out.println("[msx] before_class");' hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/tools/offlineImageViewer/TestOfflineImageViewer.java
sed -i '69a System.out.println("[msx] before_class");' hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/tools/offlineImageViewer/TestOfflineImageViewerForXAttr.java
sed -i '45a System.out.println("[msx] before_class");' hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/util/FoldedTreeSetTest.java
sed -i '54a System.out.println("[msx] before_class");' hadoop-hdfs/src/test/java/org/apache/hadoop/tracing/TestTracingShortCircuitLocalRead.java
sed -i '52a System.out.println("[msx] before_class");' hadoop-hdfs/src/test/java/org/apache/hadoop/fs/TestUrlStreamHandler.java
sed -i '32a System.out.println("[msx] before_class");' hadoop-hdfs/src/test/java/org/apache/hadoop/fs/TestSymlinkHdfsFileContext.java
sed -i '59a System.out.println("[msx] before_class");' hadoop-hdfs/src/test/java/org/apache/hadoop/fs/TestHDFSFileContextMainOperations.java
sed -i '76a System.out.println("[msx] before_class");' hadoop-hdfs/src/test/java/org/apache/hadoop/fs/TestWebHdfsFileContextMainOperations.java
sed -i '49a System.out.println("[msx] before_class");' hadoop-hdfs/src/test/java/org/apache/hadoop/fs/TestFcHdfsCreateMkdir.java
sed -i '61a System.out.println("[msx] before_class");' hadoop-hdfs/src/test/java/org/apache/hadoop/fs/viewfs/TestViewFileSystemWithXAttrs.java
sed -i '57a System.out.println("[msx] before_class");' hadoop-hdfs/src/test/java/org/apache/hadoop/fs/viewfs/TestViewFileSystemWithTruncate.java
sed -i '64a System.out.println("[msx] before_class");' hadoop-hdfs/src/test/java/org/apache/hadoop/fs/viewfs/TestViewFsFileStatusHdfs.java
sed -i '60a System.out.println("[msx] before_class");' hadoop-hdfs/src/test/java/org/apache/hadoop/fs/viewfs/TestViewFsWithXAttrs.java
sed -i '79a System.out.println("[msx] before_class");' hadoop-hdfs/src/test/java/org/apache/hadoop/fs/viewfs/TestViewFsDefaultValue.java
sed -i '53a System.out.println("[msx] before_class");' hadoop-hdfs/src/test/java/org/apache/hadoop/fs/viewfs/TestViewFileSystemAtHdfsRoot.java
sed -i '65a System.out.println("[msx] before_class");' hadoop-hdfs/src/test/java/org/apache/hadoop/fs/viewfs/TestViewFileSystemWithAcls.java
sed -i '65a System.out.println("[msx] before_class");' hadoop-hdfs/src/test/java/org/apache/hadoop/fs/viewfs/TestViewFsWithAcls.java
sed -i '79a System.out.println("[msx] before_class");' hadoop-hdfs/src/test/java/org/apache/hadoop/fs/viewfs/TestViewFileSystemLinkMergeSlash.java
sed -i '85a System.out.println("[msx] before_class");' hadoop-hdfs/src/test/java/org/apache/hadoop/fs/viewfs/TestViewFileSystemHdfs.java
sed -i '51a System.out.println("[msx] before_class");' hadoop-hdfs/src/test/java/org/apache/hadoop/fs/viewfs/TestViewFsHdfs.java
sed -i '54a System.out.println("[msx] before_class");' hadoop-hdfs/src/test/java/org/apache/hadoop/fs/viewfs/TestViewFsAtHdfsRoot.java
sed -i '78a System.out.println("[msx] before_class");' hadoop-hdfs/src/test/java/org/apache/hadoop/fs/viewfs/TestViewFileSystemLinkFallback.java
sed -i '70a System.out.println("[msx] before_class");' hadoop-hdfs/src/test/java/org/apache/hadoop/fs/permission/TestStickyBit.java
sed -i '69a System.out.println("[msx] before_class");' hadoop-hdfs/src/test/java/org/apache/hadoop/fs/TestGlobPaths.java
sed -i '32a System.out.println("[msx] before_class");' hadoop-hdfs/src/test/java/org/apache/hadoop/fs/TestSymlinkHdfsFileSystem.java
sed -i '57a System.out.println("[msx] before_class");' hadoop-hdfs/src/test/java/org/apache/hadoop/fs/TestResolveHdfsSymlink.java
sed -i '89a System.out.println("[msx] before_class");' hadoop-hdfs/src/test/java/org/apache/hadoop/fs/TestEnhancedByteBufferAccess.java
sed -i '62a System.out.println("[msx] before_class");' hadoop-hdfs/src/test/java/org/apache/hadoop/fs/TestSWebHdfsFileContextMainOperations.java
sed -i '56a System.out.println("[msx] before_class");' hadoop-hdfs/src/test/java/org/apache/hadoop/fs/TestFcHdfsPermission.java
sed -i '88a System.out.println("[msx] before_class");' hadoop-hdfs/src/test/java/org/apache/hadoop/fs/TestSymlinkHdfs.java
sed -i '86a System.out.println("[msx] before_class");' hadoop-hdfs/src/test/java/org/apache/hadoop/fs/TestFcHdfsSetUMask.java
sed -i '35a System.out.println("[msx] before_class");' hadoop-hdfs/src/test/java/org/apache/hadoop/fs/contract/hdfs/TestHDFSContractMkdir.java
sed -i '32a System.out.println("[msx] before_class");' hadoop-hdfs/src/test/java/org/apache/hadoop/fs/contract/hdfs/TestHDFSContractCreate.java
sed -i '32a System.out.println("[msx] before_class");' hadoop-hdfs/src/test/java/org/apache/hadoop/fs/contract/hdfs/TestHDFSContractRename.java
sed -i '32a System.out.println("[msx] before_class");' hadoop-hdfs/src/test/java/org/apache/hadoop/fs/contract/hdfs/TestHDFSContractSetTimes.java
sed -i '35a System.out.println("[msx] before_class");' hadoop-hdfs/src/test/java/org/apache/hadoop/fs/contract/hdfs/TestHDFSContractSeek.java
sed -i '36a System.out.println("[msx] before_class");' hadoop-hdfs/src/test/java/org/apache/hadoop/fs/contract/hdfs/TestHDFSContractRootDirectory.java
sed -i '35a System.out.println("[msx] before_class");' hadoop-hdfs/src/test/java/org/apache/hadoop/fs/contract/hdfs/TestHDFSContractConcat.java
sed -i '35a System.out.println("[msx] before_class");' hadoop-hdfs/src/test/java/org/apache/hadoop/fs/contract/hdfs/TestHDFSContractOpen.java
sed -i '35a System.out.println("[msx] before_class");' hadoop-hdfs/src/test/java/org/apache/hadoop/fs/contract/hdfs/TestHDFSContractDelete.java
sed -i '28a System.out.println("[msx] before_class");' hadoop-hdfs/src/test/java/org/apache/hadoop/fs/contract/hdfs/TestHDFSContractAppend.java
sed -i '33a System.out.println("[msx] before_class");' hadoop-hdfs/src/test/java/org/apache/hadoop/fs/contract/hdfs/TestHDFSContractGetFileStatus.java
sed -i '42a System.out.println("[msx] before_class");' hadoop-hdfs/src/test/java/org/apache/hadoop/fs/contract/hdfs/TestHDFSContractPathHandle.java
sed -i '45a System.out.println("[msx] before_class");' hadoop-hdfs/src/test/java/org/apache/hadoop/tools/TestTools.java
sed -i '66a System.out.println("[msx] before_class");' hadoop-hdfs-client/src/test/java/org/apache/hadoop/hdfs/web/TestWebHdfsContentLength.java
sed -i '77a System.out.println("[msx] before_class");' hadoop-hdfs-client/src/test/java/org/apache/hadoop/hdfs/server/namenode/ha/TestConfiguredFailoverProxyProvider.java
sed -i '65a System.out.println("[msx] before_class");' hadoop-hdfs-client/src/test/java/org/apache/hadoop/hdfs/server/namenode/ha/TestRequestHedgingProxyProvider.java
sed -i '35a System.out.println("[msx] before_class");' hadoop-hdfs-client/src/test/java/org/apache/hadoop/fs/TestXAttr.java
sed -i '50a System.out.println("[msx] before_class");' hadoop-hdfs-httpfs/src/test/java/org/apache/hadoop/fs/http/server/TestHttpFSServerWebServer.java
sed -i '236a System.out.println("[msx] before_class");' hadoop-hdfs-native-client/src/main/native/fuse-dfs/test/TestFuseDFS.java
sed -i '63a System.out.println("[msx] before_class");' hadoop-hdfs-nfs/src/test/java/org/apache/hadoop/hdfs/nfs/nfs3/TestReaddir.java
sed -i '54a System.out.println("[msx] before_class");' hadoop-hdfs-nfs/src/test/java/org/apache/hadoop/hdfs/nfs/nfs3/TestClientAccessPrivilege.java
sed -i '125a System.out.println("[msx] before_class");' hadoop-hdfs-nfs/src/test/java/org/apache/hadoop/hdfs/nfs/nfs3/TestRpcProgramNfs3.java
sed -i '47a System.out.println("[msx] before_class");' hadoop-hdfs-nfs/src/test/java/org/apache/hadoop/hdfs/nfs/nfs3/TestNfs3HttpServer.java
sed -i '87a System.out.println("[msx] before_class");' hadoop-hdfs-nfs/src/test/java/org/apache/hadoop/hdfs/nfs/nfs3/TestViewfsWithNfs3.java
sed -i '59a System.out.println("[msx] before_class");' hadoop-hdfs-rbf/src/test/java/org/apache/hadoop/hdfs/server/federation/resolver/TestNamenodeResolver.java
sed -i '59a System.out.println("[msx] before_class");' hadoop-hdfs-rbf/src/test/java/org/apache/hadoop/hdfs/server/federation/store/TestStateStoreMembershipState.java
sed -i '52a System.out.println("[msx] before_class");' hadoop-hdfs-rbf/src/test/java/org/apache/hadoop/hdfs/server/federation/store/TestStateStoreRouterState.java
sed -i '39a System.out.println("[msx] before_class");' hadoop-hdfs-rbf/src/test/java/org/apache/hadoop/hdfs/server/federation/store/driver/TestStateStoreFileSystem.java
sed -i '36a System.out.println("[msx] before_class");' hadoop-hdfs-rbf/src/test/java/org/apache/hadoop/hdfs/server/federation/store/driver/TestStateStoreFile.java
sed -i '59a System.out.println("[msx] before_class");' hadoop-hdfs-rbf/src/test/java/org/apache/hadoop/hdfs/server/federation/store/driver/TestStateStoreZK.java
sed -i '52a System.out.println("[msx] before_class");' hadoop-hdfs-rbf/src/test/java/org/apache/hadoop/hdfs/server/federation/store/TestStateStoreBase.java
sed -i '59a System.out.println("[msx] before_class");' hadoop-hdfs-rbf/src/test/java/org/apache/hadoop/hdfs/server/federation/store/TestStateStoreMountTable.java
sed -i '84a System.out.println("[msx] before_class");' hadoop-hdfs-rbf/src/test/java/org/apache/hadoop/hdfs/server/federation/router/TestRouterAdmin.java
sed -i '58a System.out.println("[msx] before_class");' hadoop-hdfs-rbf/src/test/java/org/apache/hadoop/hdfs/server/federation/router/TestRouterSafemode.java
sed -i '70a System.out.println("[msx] before_class");' hadoop-hdfs-rbf/src/test/java/org/apache/hadoop/hdfs/server/federation/router/TestDisableNameservices.java
sed -i '64a System.out.println("[msx] before_class");' hadoop-hdfs-rbf/src/test/java/org/apache/hadoop/hdfs/server/federation/router/TestRouterMountTable.java
sed -i '53a System.out.println("[msx] before_class");' hadoop-hdfs-rbf/src/test/java/org/apache/hadoop/hdfs/server/federation/router/TestRouter.java
sed -i '163a System.out.println("[msx] before_class");' hadoop-hdfs-rbf/src/test/java/org/apache/hadoop/hdfs/server/federation/router/TestRouterRpc.java
sed -i '55a System.out.println("[msx] before_class");' hadoop-hdfs-rbf/src/test/java/org/apache/hadoop/hdfs/server/federation/router/TestRouterNamenodeHeartbeat.java
sed -i '78a System.out.println("[msx] before_class");' hadoop-hdfs-rbf/src/test/java/org/apache/hadoop/hdfs/server/federation/router/TestRouterAdminCLI.java
sed -i '42a System.out.println("[msx] before_class");' hadoop-hdfs-rbf/src/test/java/org/apache/hadoop/hdfs/server/federation/router/TestDisableRouterQuota.java
sed -i '35a System.out.println("[msx] before_class");' hadoop-hdfs-rbf/src/test/java/org/apache/hadoop/fs/contract/router/TestRouterHDFSContractRename.java
sed -i '36a System.out.println("[msx] before_class");' hadoop-hdfs-rbf/src/test/java/org/apache/hadoop/fs/contract/router/TestRouterHDFSContractSetTimes.java
sed -i '36a System.out.println("[msx] before_class");' hadoop-hdfs-rbf/src/test/java/org/apache/hadoop/fs/contract/router/TestRouterHDFSContractConcat.java
sed -i '35a System.out.println("[msx] before_class");' hadoop-hdfs-rbf/src/test/java/org/apache/hadoop/fs/contract/router/TestRouterHDFSContractCreate.java
sed -i '36a System.out.println("[msx] before_class");' hadoop-hdfs-rbf/src/test/java/org/apache/hadoop/fs/contract/router/TestRouterHDFSContractGetFileStatus.java
sed -i '36a System.out.println("[msx] before_class");' hadoop-hdfs-rbf/src/test/java/org/apache/hadoop/fs/contract/router/web/TestRouterWebHDFSContractRootDirectory.java
sed -i '35a System.out.println("[msx] before_class");' hadoop-hdfs-rbf/src/test/java/org/apache/hadoop/fs/contract/router/web/TestRouterWebHDFSContractMkdir.java
sed -i '36a System.out.println("[msx] before_class");' hadoop-hdfs-rbf/src/test/java/org/apache/hadoop/fs/contract/router/web/TestRouterWebHDFSContractDelete.java
sed -i '36a System.out.println("[msx] before_class");' hadoop-hdfs-rbf/src/test/java/org/apache/hadoop/fs/contract/router/web/TestRouterWebHDFSContractCreate.java
sed -i '36a System.out.println("[msx] before_class");' hadoop-hdfs-rbf/src/test/java/org/apache/hadoop/fs/contract/router/web/TestRouterWebHDFSContractRename.java
sed -i '37a System.out.println("[msx] before_class");' hadoop-hdfs-rbf/src/test/java/org/apache/hadoop/fs/contract/router/web/TestRouterWebHDFSContractConcat.java
sed -i '32a System.out.println("[msx] before_class");' hadoop-hdfs-rbf/src/test/java/org/apache/hadoop/fs/contract/router/web/TestRouterWebHDFSContractAppend.java
sed -i '36a System.out.println("[msx] before_class");' hadoop-hdfs-rbf/src/test/java/org/apache/hadoop/fs/contract/router/web/TestRouterWebHDFSContractOpen.java
sed -i '35a System.out.println("[msx] before_class");' hadoop-hdfs-rbf/src/test/java/org/apache/hadoop/fs/contract/router/web/TestRouterWebHDFSContractSeek.java
sed -i '35a System.out.println("[msx] before_class");' hadoop-hdfs-rbf/src/test/java/org/apache/hadoop/fs/contract/router/TestRouterHDFSContractDelete.java
sed -i '35a System.out.println("[msx] before_class");' hadoop-hdfs-rbf/src/test/java/org/apache/hadoop/fs/contract/router/TestRouterHDFSContractSeek.java
sed -i '35a System.out.println("[msx] before_class");' hadoop-hdfs-rbf/src/test/java/org/apache/hadoop/fs/contract/router/TestRouterHDFSContractMkdir.java
sed -i '35a System.out.println("[msx] before_class");' hadoop-hdfs-rbf/src/test/java/org/apache/hadoop/fs/contract/router/TestRouterHDFSContractOpen.java
sed -i '31a System.out.println("[msx] before_class");' hadoop-hdfs-rbf/src/test/java/org/apache/hadoop/fs/contract/router/TestRouterHDFSContractAppend.java
sed -i '36a System.out.println("[msx] before_class");' hadoop-hdfs-rbf/src/test/java/org/apache/hadoop/fs/contract/router/TestRouterHDFSContractRootDirectory.java
